-- Project 1: Customer Analysis
-- Analyzing top customers, total revenue, and average rentals

-- 1️. Total revenue across all customers
-- Interpretation: This is the total revenue generated by the business.
SELECT SUM(p.amount) AS total_revenue
FROM payment p;

-- 2️. Total number of customers
-- Interpretation: There are 599 unique customers in the database.
SELECT COUNT(DISTINCT c.customer_id) AS total_customers
FROM customer c;

-- 3️. Top 10 customers total revenue and % of total revenue
-- Interpretation: The top 10 customers contribute $1,844.16, which is ~3% of total revenue.
-- Shows a broad and evenly distributed customer base.
-- Create a view for top 10 customers by total spending
CREATE OR REPLACE VIEW top_10_customers AS
SELECT c.customer_id, SUM(p.amount) AS total_spent
FROM customer c
JOIN payment p 
    ON c.customer_id = p.customer_id
GROUP BY c.customer_id
ORDER BY total_spent DESC
LIMIT 10;
-- Use the top_10_customers view to calculate total revenue and percent of overall revenue
SELECT SUM(total_spent) AS top10_total_revenue,
  ROUND(SUM(total_spent) * 100.0 / (SELECT SUM(amount) FROM payment), 2) AS percent_of_total_revenue
FROM top_10_customers;

-- 4️. Average rentals per customer is 26.78.
SELECT AVG(rental_count) AS avg_rentals_per_customer
FROM (
    SELECT COUNT(r.rental_id) AS rental_count
    FROM rental r
    GROUP BY r.customer_id);